## Semana 5: Data Wrangling (IBM)

## Profesor : Jobish Vallikavungal Devassia

## Materia   : Ciencia y anal√≠tica de datos

### Kevin Alejandro Garcia Escalante                                    A01376680


### Fecha : 18 de Octubre de 2022

In [2]:
import pandas as pd
import numpy as np

#### Lab 2: Review Data Wrangling (External resource)

In [3]:
example1 = "imports__85.data"
file = open(example1, "r")

In [4]:
dff = pd.read_csv(example1, header=None)
dff

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [5]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [6]:
dff.columns = headers
dff

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

#### Q1: Based on the example above, replace NaN in "stroke" column with the mean value.

In [7]:
dff.replace("?", np.nan, inplace = True)

In [8]:
# Calcular la media
avg_stroke = dff["stroke"].astype("float").mean(axis = 0)
print("Average of stroke:", avg_stroke)

# Reemplazar Nan 
dff["stroke"].replace(np.nan, avg_stroke, inplace = True)

Average of stroke: 3.255422885572139

#### Q2: According to the example above, transform mpg to L/100km in the column of "highway-mpg" and change the name of column to "highway-L/100km".

In [9]:
# Transfomarcion de unidades
dff["highway-mpg"] = 235/dff["highway-mpg"]

# Cambiar nombre "highway-mpg" a "highway-L/100km"
dff.rename(columns={'highway-mpg':'highway-L/100km'}, inplace=True)

# Revisar 
dff.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-L/100km,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,8.703704,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,8.703704,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,9.038462,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,7.833333,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,10.681818,17450

#### Q3: According to the example above, normalize the column "height".

In [10]:
dff['height'] = dff['height']/dff['height'].max() 

# Mostrar las escalas
dff[["length","width","height"]].head()

   length  width    height
0   168.8   64.1  0.816054
1   168.8   64.1  0.816054
2   171.2   65.5  0.876254
3   176.6   66.2  0.908027
4   176.6   66.4  0.908027

#### Q4: Similar to before, create an indicator variable for the column "aspiration"

In [11]:
# Agregar indicador de variables
dummy_variable_2 = pd.get_dummies(dff['aspiration'])

# CAmbiar nombre de columnas
dummy_variable_2.rename(columns={'std':'aspiration-std', 'turbo': 'aspiration-turbo'}, inplace=True)

# Mostrar las primeras 5
dummy_variable_2.head()

   aspiration-std  aspiration-turbo
0               1                 0
1               1                 0
2               1                 0
3               1                 0
4               1                 0

#### Q5: Merge the new dataframe to the original dataframe, then drop the column 'aspiration'.

In [12]:
# JUntar el dataframe al original
dff = pd.concat([dff, dummy_variable_2], axis=1)

dff

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-L/100km,price,aspiration-std,aspiration-turbo
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,8.703704,13495,1,0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,8.703704,16500,1,0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,9.038462,16500,1,0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102,5500,24,7.833333,13950,1,0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115,5500,18,10.681818,17450,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,23,8.392857,16845,1,0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,8.7,160,5300,19,9.400000,19045,0,1
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.58,2.87,8.8,134,5500,18,10.217391,21485,1,0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.01,3.40,23.0,106,4800,26,8.703704,22470,0,1
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,19,9.400000,22625,0,1

#### Q1 Consider the dataframe df. What is the result of the following operation: df['symbolling'] = df['symbolling'] + 1?

In [13]:
#RESP: Every element in the column "symbolling" will increase by one.

#### Q2 Consider the dataframe df. What does the command df.rename(columns={'a':'b'}) change about the dataframe df?

In [14]:
#RESP: Nothing. You must set the parameter "inplace = True".

#### Q3: Consider the dataframe "df". What is the result of the following operation df['price'] = df['price'].astype(int)?

In [15]:
#RESP: Convert or cast the column 'price' to an integer value.

#### Q4:Consider the column of the dataframe df['a']. The column has been standardized. What is the standard deviation of the values as a result of applying the following operation: df['a'].std()?

In [16]:
#RESP: 1

#### Q5: Consider the column of the dataframe, df['Fuel'], with two values: 'gas' and' diesel'. What will be the name of the new columns pd.get_dumies(df['Fuel']) ?

In [17]:
#RESP: 'gas' and 'diesel'

#### Q6: What are the values of the new columns from part 5a)?

In [18]:
#RESP: 1 and 0

In [19]:
np.array([1,-1]) + np.array([-1,1])

array([0, 0])